name: lua check

on:
  push:
    paths:
      - "**.lua"

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@v4
      - uses: lunarmodules/luacheck@v1.2.0
        with:
          args: --globals vim Snacks -- .
      - uses: JohnnyMorganz/stylua-action@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
